# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

---
specSchema: "DeploymentPackage"
schemaVersion: "0.1"
$schema: "https://schema.intel.com/catalog.orchestrator/0.1/schema"

name: "baseline-extensions-lite"
description: "Baseline Extensions Lite"
version: 0.1.0
forbidsMultipleDeployments: true
kind: extension

applications:
  - name: baseline-extension-lite
    version: 1.14.3

defaultNamespaces:
  baseline-extension-lite: cert-manager

deploymentProfiles:
  - name: "baseline-lite"
    displayName: "Baseline Cluster Template Lite"
    applicationProfiles:
      - application: baseline-extension-lite
        profile: default
