# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ServiceAccount
metadata:
  name: cattle-impersonation-u-fake
  namespace: cattle-impersonation-system
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: cattle-impersonation-u-fake-token
  namespace: cattle-impersonation-system
  annotations:
    kubernetes.io/service-account.name: cattle-impersonation-u-fake
