# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

# The rule definition can be found
# https://github.com/updownpress/markdown-lint/tree/master/rules

config:
  MD013:
    line_length: 120
    code_blocks: false

ignores:
  - "**/.terraform/**"
