# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Secret
metadata:
  name: smtp
type: Opaque
stringData:
  smartHost: mailpit-svc.mailpit-dev.svc.cluster.local
  smartPort: "1025"
  from: foo@bar.com
  authUsername: foo@smtp.example.org
